config/routes.rb
Rails.application.routes.draw do
  root "homes#show"
  resource :home, only: :show
  resources :applications, only: [:new, :create]
end

app/models/application.rb
class Application < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  respond_to :html

  def new
    @application = Application.new
    respond_with(@application)
  end

  def create
    @application = Application.create(application_params)
    respond_with(@application, location: home_path)
  end

  private

  def application_params
    params.require(:application).permit(:name, :email)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  respond_to :html

  def show
    respond_with(1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/applications/new.html.haml
= form_for(@application) do |f|
  %dl
    %dt Name
    %dd= f.text_field :name

    %dt Email
    %dd= f.text_field :email

    %dt When did you first start programming?  In what language, and in what circumstances?
    %dd= f.text_area :answer1

    %dt What made you decide on a career in software development?
    %dd= f.text_area :answer2

    %dt What, if anything, do you dislike about software development?
    %dd= f.text_area :answer3

    %dt What single thing most changed the way you think about software, or working in software?
    %dd= f.text_area :answer4

  = f.submit

app/views/homes/show.html.haml
%header
  = image_tag('alice.png', class: 'alice')
  = image_tag('title.png', class: 'title')

%div
  %h2 We're a new software consultancy.

  %p
    Interested in learning more?
    = link_to 'Get in touch.', 'mailto:info@buildgroundwork.com'

  %p
    Interested in working here?
    = link_to 'Apply here.', new_application_path

%footer
  %div
    %ul
      %li= link_to 'info@buildgroundwork.com', 'mailto:info@buildgroundwork.com'
      %li
        = render 'homes/github_icon'
        = link_to 'buildgroundwork', 'http://www.github.com/buildgroundwork'
      %li
        = render 'homes/twitter_icon'
        = link_to 'buildgroundwork', 'http://www.twitter.com/buildgroundwork'

  %p © 2014 Groundwork. Lovingly made in New York City.

app/views/layouts/application.html.haml
!!!
%html
%head
  %title Website
  = stylesheet_link_tag 'application', media: 'all'
  = javascript_include_tag 'application'
  = csrf_meta_tags

%body
  = yield